// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWN2tu7tQ0XKUEXAFOkpRTqutM7i34vDY',
    appId: '1:723524784360:web:ee74679f393bcdeedc795d',
    messagingSenderId: '723524784360',
    projectId: 'flybook-a5866',
    authDomain: 'flybook-a5866.firebaseapp.com',
    storageBucket: 'flybook-a5866.firebasestorage.app',
    measurementId: 'G-5QLL7P31TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAefzAUCh1pJ3LJHhSGV5tQ9vpnJ3aYxwk',
    appId: '1:723524784360:android:d6d4de207db5ec5edc795d',
    messagingSenderId: '723524784360',
    projectId: 'flybook-a5866',
    storageBucket: 'flybook-a5866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADfSO10FihQXVcKY0DKFhsC9cJO1Qv4kM',
    appId: '1:723524784360:ios:143e56ddebed86fedc795d',
    messagingSenderId: '723524784360',
    projectId: 'flybook-a5866',
    storageBucket: 'flybook-a5866.firebasestorage.app',
    iosBundleId: 'com.example.flybook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADfSO10FihQXVcKY0DKFhsC9cJO1Qv4kM',
    appId: '1:723524784360:ios:143e56ddebed86fedc795d',
    messagingSenderId: '723524784360',
    projectId: 'flybook-a5866',
    storageBucket: 'flybook-a5866.firebasestorage.app',
    iosBundleId: 'com.example.flybook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWN2tu7tQ0XKUEXAFOkpRTqutM7i34vDY',
    appId: '1:723524784360:web:e2d1f6f85fd6f2c4dc795d',
    messagingSenderId: '723524784360',
    projectId: 'flybook-a5866',
    authDomain: 'flybook-a5866.firebaseapp.com',
    storageBucket: 'flybook-a5866.firebasestorage.app',
    measurementId: 'G-S4J6RERGCP',
  );
}